services:
  # Our PostgreSQL database
  db:
    image: postgres:16
    ports:
      - "5450:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

 # Database management interface - visual representation of db
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    # Persists volumes between restarts
    volumes:
      - keycloak-data:/opt/keycloak/data
    command:
      - start-dev
      - --db=dev-file

volumes:
  keycloak-data:
    driver: local